/*
 * This source file was generated by the Gradle 'init' task
 */
package org.mhetrerajat;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mhetrerajat.integrations.service.GreetingService;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
class AppTest {

    @Mock
    private GreetingService greetingService;

    @InjectMocks
    private App app;

    @Test
    void appHasAGreeting_givenDefaultParameters_returnSuccess() {

        // Mock
        when(greetingService.getGreeting()).thenReturn("Test Greeting");

        // Assert
        assertNotNull(app.getGreeting(), "app should have a greeting");
        assertNotNull(app);
    }
}
